### ISSUE TITLE
Visual Studio Code 연동 문제

### ISSUE THREAD

**Issue by nynyny95** [plasticver2/react-git#1]
복제까지 성공했으나 푸쉬 작업이 되지 않습니다!

**Comment by yunhyeonji** [comment]
저도 터미널에서 하니까 오류가 뜹니다!!
 ! [remote rejected] HJ -> HJ (protected branch hook declined)
error: failed to push some refs to 'https://github.com/plasticver2/react-git.git'

**Comment by nynyny95** [comment]
브런치 해결해주시고 나서는 아쥬 잘 됩니다 호호^0^
